bot:
#  name: ${BOT_NAME}
#  token: ${BOT_TOKEN}
  name: notebookmanager_bot
  token: 5048393640:AAGA0cYs7DKEm92a6v_QcTDUEFVkIX0p87Q

  commands:
  - /newnote
  - /deletenote
  - /showall
  - /getnote
  - /start
  - /help
  - /getfile
  - /editnote
